### ISSUE TITLE
Criação de Roadmap do Projeto

### ISSUE THREAD

**Issue by Punkrig** [ResidenciaTICBrisa/T2G8-Plugin-Wordpress#17]
# Etapas para validação:

- [x] Conter as sprints do projeto
- [x] Conter os User Story do backlog
- [x] Gráfico mostrando a evolução do projeto

## Resumo sobre:

A criação e edição do roadmap do projeto, adicionando informações sobre quando e o que foi feito.
